"""add_address_and_bank_info_to_users

Revision ID: 1234567890ab
Revises: 2025_11_29_1400-add_case_stages
Create Date: 2025-11-29 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1234567890ab'
down_revision = 'ghi789012345'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_account_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bank_account_info')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
